### ISSUE TITLE
Adding Fleet to Konductor

### ISSUE THREAD

**Issue by aag6z** [sunileman/ElasticKonductor#17]
Changes that were made:

1) Added `remote_cluster_client` role to all nodes (don't know why trying to get an answer...) 
2) Had to add more rules to the `ClusterRole` for Fleet Server (trying to narrow down exactly what those are)
3) Had to create a new custom output and explicitly set 
``` 
config:
          ssl:
            verification_mode: none
```
4) Had to add that output to each policy
```
 - name: Elastic Agent on ECK policy
      id: eck-agent
      namespace: default
      data_output_id: "output_custom_host"
      monitoring_output_id: "output_custom_host"
      monitoring_enabled:
      - logs
      - metrics
      unenroll_timeout: 900
      package_policies:
      - package:
          name: system
        name: system-1
      - package:
          name: kubernetes
        name: kubernetes-1
```

This sets up Fleet but Agent needs to be deployed with the manifest created by Fleet - it's easier than trying to preconfigure that. Change KSM endpoint.

Note: there's a bug in the GCP code 

```
+++ b/gcp/eck/eck-yamls/es.yaml
@@ -471,4 +471,4 @@ spec:
    tls:
     selfSignedCertificate:
      subjectAltNames:
-     - dns: "*.cloudapp.azure.com"
+     - dns: "*.googleusercontent.com"
```
